accounts/urls.py
from django.urls import path
from form_app import views

#TEMPLATE urls
app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name = 'logout'),
    path('forgot_password/', views.forgot_password, name = 'forgot_password'),
    path('reset_password/', views.reset_password, name = 'reset_password'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),

]

form_project/urls.py
from django.contrib import admin
from django.urls import path, include
from form_app import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('form_data/', views.form_data, name='form_data'),
    path('confirmation/', views.confirmation, name='confirmation'),
    path('accounts/',include('accounts.urls')),
    path('dashboard/', views.dashboard, name = 'dashboard'),
    #path('form_data/', views.form_data, name='form_data')

]+static(settings.DOC_URL, document_root = settings.DOC_ROOT)

templates/account_ verification_email.html
{% autoescape off %}
{% csrf_token %}
Hi {{user.first_name}},

Please click on the below link to confirm your registration:
http://{{domain}}{% url 'accounts:activate' uidb64=uid token=token %}

If you think it's not you, please ignore this email.

{% endautoescape %}

templates/alerts.html
{% if messages %}

   {% for message in messages %}
       <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
            {{ message }}
        </div>
    {% endfor %}

{% endif %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">

  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'mystyle.css' %}">
    <!-- Latest compiled and minified CSS -->
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <title>Resume and Skills</title>
  </head>

<style >
  .center {
  margin: auto;
  }

  .container2 {
      width: 350px;
      height: 800px;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      margin: auto;
      border: 2px solid White;
      border-radius: 15px;
      background: white;
  }

  .container3 {
      width: 650px;
      height: 800px;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      margin: auto;
      border: 2px solid White;
      border-radius: 15px;
      background: white;
  }

  .form-item {
      width: 320px;
      height: 35px;
      border-radius: 20px;
  }

  .form-btns  {
      margin: auto;
      font-size: 20px;
      padding: 5px 15px;
      border: 2px solid;
      border-radius: 15px;
      color: white;
      background: #178cc6;
      width: 280px;
      cursor: pointer;
  }

  .options {
      padding-top: 15px;
  }

  .options a {
      text-decoration: none;
      color: black;
      margin: 0 40px;
      font-family: Arial, Helvetica, sans-serif;
      font-size: 15px;
  }
  .options a:hover {
      color: grey;

  }

</style>

  <body background = 'static/bg1.jpg'>
    <nav class="navbar navbar-light fixed-top" style="background-color: #56A5EC;">
      <div class="container">
        <ul class = ' nav navbar-nav '>

          {% if user.is_authenticated %}
          <li> <a class = 'navbar-brand' href="#" style="color:black" >Welcome {{user.first_name}}</a> </li>
        </ul>
        <ul class = ' nav navbar-nav ms-auto'>

           <li> <a class = 'navbar-link'  href="{% url 'accounts:logout' %}" style="color:black" >Logout</a></li>
          {% else %}
           <li> <a class = 'navbar-link'  href="{% url 'index' %}" style="color:black" >Login</a></li>
          {% endif %}

          </ul>


      </div>

    </nav>
    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>
  </body>
</html>

templates/confirmation.html
{% extends 'base.html' %}
{% block body_block %}

<div style = 'position:absolute; top:150px; left:150px; height:150px;' >

  <h4>Your details have been successfully uploaded!!!</h4>

</div>

{% endblock %}

templates/dashboard.html
{% extends 'base.html' %}
{% block body_block %}

<style>
  table, th, td {
    border: 2px solid; font-size: 20px; text-align: centre;
  }
</style>

<div class="row"; style="position:absolute; top:10px; left:10px;">
  <div calss="column"; style="position:absolute; top:1px; left:5px;">
    <img src="/docs/charts/chart1.png" alt="Average Salary" srcset="">
    <div style = "position:absolute; top:300px; left:550px;">
    </div>
  </div>
  <div calss="column"; style="position:absolute; top:1px; left:700px;">
    <img src="/docs/charts/chart2.png" alt="Available Candidates" srcset="">
    <div style = "position:absolute; top:300px; left:500px;">
    </div>
  </div>
</div>
<div style = 'position:absolute; top:500px; left:150px; overflow-y: auto; width: 1300px; height: 200px;' >
  {% autoescape off %}
    {{detail}}
  {% endautoescape %}
</div>

{% endblock %}

templates/forgot_password.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">

    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exl</title>
    <style>
        html {
            background: #6696cc;
        }

        .body-content {
            padding-top: 20vh;
        }

        .container {
            width: 350px;
            height: 400px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            margin: auto;
            border: 2px solid White;
            border-radius: 15px;
            background: white;
        }

        .logo {
            margin-bottom: 15px;
            margin-top: 0px;
            padding-top: 0;
        }

        .logo img {
            width: 150px;
            margin: 10px;
            border-radius: 50px;
        }

        form {
            display: flex;
            flex-direction: column;
        }

        .form-item {
            margin: 5px;
            padding-bottom: 10px;
            display: flex;
        }

        .form-item label {
            display: block;
            padding: 2px;
            font-size: 20px;
            width: 100px;
        }

        .form-item input {
            width: 320px;
            height: 35px;
            border: 2px solid #e1dede69;
            border-radius: 20px;
            background: #e1dede69;
            color: grey;
        }

        .form-btns {
            display: flex;
            flex-direction: column;
            margin: auto;
            padding: 10px 0;
        }

        .form-btns button {
            margin: auto;
            font-size: 20px;
            padding: 5px 15px;
            border: 2px solid;
            border-radius: 15px;
            color: white;
            background: #178cc6;
            width: 280px;
            cursor: pointer;
        }

        .options {
            padding-top: 15px;
            margin: auto;
        }

        .options a {
            text-decoration: none;
            color: black;
            margin: 0 40px;
            font-family: Arial, Helvetica, sans-serif;
            font-size: 15px;

        }
        .options a:hover {
            color: grey;

        }

        p {
            text-align: center;
            font-size: 10px;
            font-family: Arial, Helvetica, sans-serif;
        }
    </style>
</head>

<body>

    <div class="body-content">
        <div class="container">
          <h4>Enter your registered email:</h4>

            <div class="login-form">

                <form action="{% url 'accounts:forgot_password' %}" method="post">
                  {% csrf_token %}
                    {% include 'alerts.html' %}
                    <div class="form-item">
                        <!-- <label for="userName">Username:</label> -->
                        <input type="email" name="email"  placeholder="Email">
                    </div>

                    <div class="form-btns">

                        <button type="submit">Submit</button>
                        <div class="options">
                            <a href="{% url 'index' %}">Got Password? Login</a>
                        </div>


                    </div>
                </form>
                <p>Copyright &copy; DSAE.com</p>
            </div>
        </div>


    </div>



</body>

</html>

templates/form.html
</h7>{% extends 'base.html' %}
{% block body_block %}

<div class="container3"'>

  <form  action="{% url 'form_data' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>{{ form.non_field_errors }}</p>
      <p>{{ form.document.label_tag }} {{form.document.help_text}}</p>
      <p>
        {{ form.document.errors }}
        {{ form.document }}
      </p>
      <br>
      <h7>Select your domain:</h7>
      <br>
        {{ form.domain }}
        <br>
        <br>
      <h7>Years of Experience:</h7>
      <br>
        {{ form.exp_years }}
        <br>
        <br>
      <h7>Current Salary:</h7>
        <br>
        {{ form.salary }}
        <br>
        <br>
      <h7>Expected Salary:</h7>
      <br>
        {{ form.exp_salary }}
        <br>
        <br>
      <h7>Enter your key technical skills(comma seperated):</h7>
      <br>
        {{ form.skillset }}

      <br>
      <br>
      <p> <input type="submit" value='Submit' name='form_load' class="form-btns"> </p>

  </form>

  </div>
  {% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">

    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Career</title>
    <style>
        html {
            background: #6696cc;
        }

        .body-content {
            padding-top: 20vh;
        }

        .container {
            width: 350px;
            height: 400px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            margin: auto;
            border: 2px solid White;
            border-radius: 15px;
            background: white;
        }

        .logo {
            margin-bottom: 15px;
            margin-top: 0px;
            padding-top: 0;
        }

        .logo img {
            width: 150px;
            margin: 10px;
            border-radius: 50px;
        }

        form {
            display: flex;
            flex-direction: column;
        }

        .form-item {
            margin: 5px;
            padding-bottom: 10px;
            display: flex;
        }

        .form-item label {
            display: block;
            padding: 2px;
            font-size: 20px;
            width: 100px;
        }

        .form-item input {
            width: 320px;
            height: 35px;
            border: 2px solid #e1dede69;
            border-radius: 20px;
            background: #e1dede69;
            color: grey;
        }

        .form-btns {
            display: flex;
            flex-direction: column;
            margin: auto;
            padding: 10px 0;
        }

        .form-btns button {
            margin: auto;
            font-size: 20px;
            padding: 5px 15px;
            border: 2px solid;
            border-radius: 15px;
            color: white;
            background: #178cc6;
            width: 280px;
            cursor: pointer;
        }

        .options {
            padding-top: 15px;
            margin: auto;
        }

        .options a {
            text-decoration: none;
            color: black;
            margin: 0 40px;
            font-family: Arial, Helvetica, sans-serif;
            font-size: 15px;

        }
        .options a:hover {
            color: grey;

        }

        p {
            text-align: center;
            font-size: 10px;
            font-family: Arial, Helvetica, sans-serif;
        }
    </style>
</head>

<body>

    <div class="body-content">
        <div class="container">
            <div class="logo">
                <img src="static/res.png" alt="Company Logo" srcset="">
            </div>

            <div class="login-form">

                <form action="{% url 'accounts:user_login' %}" method="post">
                  {% csrf_token %}
                    {% include 'alerts.html' %}
                    <div class="form-item">
                        <!-- <label for="userName">Username:</label> -->
                        <input type="text" name="email"  placeholder="Email">
                    </div>
                    <div class="form-item">
                        <!-- <label for="passWord">Password:</label> -->
                        <input type="password" name="password"  placeholder="Password">
                    </div>

                    <div class="form-btns">

                        <button type="submit">Login</button>
                        <div class="options">
                            <a href="{% url 'accounts:register' %}">Sign Up</a>
                            <a href="{% url 'accounts:forgot_password' %}">Reset Password</a>
                        </div>


                    </div>
                </form>
                <p>Copyright &copy; pynest.com</p>
            </div>
        </div>


    </div>



</body>

</html>

templates/password_reset_email.html
{% autoescape off %}

Hi {{user.first_name}},

As requested, please click on the below link to reset your password:
http://{{domain}}{% url 'accounts:resetpassword_validate' uidb64=uid token=token %}

If you think it's not you, please ignore this email.

{% endautoescape %}

templates/register.html
{% extends 'base.html' %}
{% block body_block %}

<div class="container2">
  {% include 'alerts.html' %}
  <h4>Register here</h4>
  <br>
  <form  action="{% url 'accounts:register' %}" method="POST" >
    {% csrf_token %}
    
    <div class="form-item">
      {{ form.first_name }}
    </div>
      <br>
      <div class="form-item">
      {{ form.last_name }}
    </div>
      <br>
      <div class="form-item">
      {{ form.email }}
    </div>
      <br>
    <div class="form-item">
      {{ form.phone_number }}
    </div>
      <br>
      <div class="form-item">
      {{ form.password }}
    </div>
      <br>
      <div class="form-item">
      {{ form.confirm_password }}
    </div>
      <br>

    <p> <input type="submit" value='Register' name='register' class="form-btns"> </p>
    {{ form.email.errors }}
    {{ form.non_field_errors }}

  </form>
  <div class="options">
      <a href="{% url 'index' %}">Got Password? Login</a>
  </div>
</div>

{% endblock %}

templates/reset_password.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">

    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Exl</title>
    <style>
        html {
            background: #6696cc;
        }

        .body-content {
            padding-top: 20vh;
        }

        .container {
            width: 350px;
            height: 400px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            margin: auto;
            border: 2px solid White;
            border-radius: 15px;
            background: white;
        }

        .logo {
            margin-bottom: 15px;
            margin-top: 0px;
            padding-top: 0;
        }

        .logo img {
            width: 150px;
            margin: 10px;
            border-radius: 50px;
        }

        form {
            display: flex;
            flex-direction: column;
        }

        .form-item {
            margin: 5px;
            padding-bottom: 10px;
            display: flex;
        }

        .form-item label {
            display: block;
            padding: 2px;
            font-size: 20px;
            width: 100px;
        }

        .form-item input {
            width: 320px;
            height: 35px;
            border: 2px solid #e1dede69;
            border-radius: 20px;
            background: #e1dede69;
            color: grey;
        }

        .form-btns {
            display: flex;
            flex-direction: column;
            margin: auto;
            padding: 10px 0;
        }

        .form-btns button {
            margin: auto;
            font-size: 20px;
            padding: 5px 15px;
            border: 2px solid;
            border-radius: 15px;
            color: white;
            background: #178cc6;
            width: 280px;
            cursor: pointer;
        }

        .options {
            padding-top: 15px;
            margin: auto;
        }

        .options a {
            text-decoration: none;
            color: black;
            margin: 0 40px;
            font-family: Arial, Helvetica, sans-serif;
            font-size: 15px;

        }
        .options a:hover {
            color: grey;

        }

        p {
            text-align: center;
            font-size: 10px;
            font-family: Arial, Helvetica, sans-serif;
        }
    </style>
</head>

<body>

    <div class="body-content">
        <div class="container">
          <h4>Enter and confirm your new password:</h4>

            <div class="login-form">

                <form action="{% url 'accounts:reset_password' %}" method="post">
                  {% csrf_token %}
                    {% include 'alerts.html' %}
                    <div class="form-item">
                        <!-- <label for="userName">Username:</label> -->
                        <input type="password" name="password"  placeholder="Enter password">
                    </div>

                    <div class="form-item">
                        <!-- <label for="userName">Username:</label> -->
                        <input type="password" name="confirm_password"  placeholder="Confirm Password">
                    </div>

                    <div class="form-btns">

                        <button type="submit">Reset</button>
                        <div class="options">
                            <a href="{% url 'index' %}">Got Password? Login</a>
                        </div>


                    </div>
                </form>
                <p>Copyright &copy; DSAE.com</p>
            </div>
        </div>


    </div>



</body>

</html>